version: '1'
services:
  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000
    #volumes:
    #  - ./clickhouse_data/:/var/lib/clickhouse/
    #  - ./clickhouse_logs/:/var/log/clickhouse-server/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
